create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  draw_no int not null unique,
  draw_date date not null,
  n1 int not null check (n1 between 1 and 45),
  n2 int not null check (n2 between 1 and 45),
  n3 int not null check (n3 between 1 and 45),
  n4 int not null check (n4 between 1 and 45),
  n5 int not null check (n5 between 1 and 45),
  n6 int not null check (n6 between 1 and 45),
  bonus int check (bonus between 1 and 45),
  first_prize_amount text,
  first_winner_count int,
  created_at timestamptz default now(),
  constraint lotto_numbers_unique check (
    n1 <> n2 and n1 <> n3 and n1 <> n4 and n1 <> n5 and n1 <> n6 and
    n2 <> n3 and n2 <> n4 and n2 <> n5 and n2 <> n6 and
    n3 <> n4 and n3 <> n5 and n3 <> n6 and
    n4 <> n5 and n4 <> n6 and
    n5 <> n6
  ),
  constraint lotto_bonus_unique check (
    bonus is null or (bonus not in (n1, n2, n3, n4, n5, n6))
  )
);

create index if not exists lotto_draws_draw_no_idx on public.lotto_draws(draw_no desc);

create table if not exists public.generated_sets (
  id bigint generated by default as identity primary key,
  method text not null,
  numbers int[] not null,
  score numeric,
  memo text,
  created_at timestamptz default now()
);

create table if not exists public.lotto_update_logs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('success', 'error')),
  message text,
  saved_count int not null default 0,
  draw_nos int[] not null default '{}',
  error_message text,
  source text not null default 'cron',
  created_at timestamptz default now()
);

-- 구버전 호환용 테이블입니다. 새 코드는 lotto_update_logs를 사용합니다.
create table if not exists public.update_logs (
  id bigint generated by default as identity primary key,
  draw_no int,
  status text not null,
  message text,
  created_at timestamptz default now()
);

alter table public.lotto_draws enable row level security;
alter table public.generated_sets enable row level security;
alter table public.lotto_update_logs enable row level security;
alter table public.update_logs enable row level security;

drop policy if exists "public read lotto_draws" on public.lotto_draws;
create policy "public read lotto_draws"
  on public.lotto_draws for select
  using (true);

drop policy if exists "public read generated_sets" on public.generated_sets;
create policy "public read generated_sets"
  on public.generated_sets for select
  using (true);

-- insert/update/delete는 service role key를 쓰는 서버 API에서만 수행합니다.
